export const GET_ERRORS = 'GET_ERRORS';
export const LOG_OUT_CLEAR = 'LOG_OUT_CLEAR';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const GET_USERS = 'GET_USERS';

export const GET_DUMMY_DATA = 'GET_DUMMY_DATA';

export const GET_POSTS = 'GET_POSTS';
export const ADD_POST = 'ADD_POST';
export const REMOVE_POST = 'REMOVE_POST';

export const GET_REQUESTS = 'GET_REQUESTS';
export const ADD_PENDING_FOLLOWER = 'ADD_PENDING_FOLLOWER';
export const ADD_APPROVED_FOLLOWER = 'ADD_APPROVED_FOLLOWER';
export const REMOVE_APPROVED_FOLLOWER = 'REMOVE_APPROVED_FOLLOWER';
