export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_USERS = 'SET_USERS';

export const SET_POSTS = 'SET_POSTS';
export const ADD_POST = 'ADD_POST';
export const REMOVE_POST = 'REMOVE_POST';

export const SET_REQUESTS = 'SET_REQUESTS';
export const ADD_PENDING_FOLLOWER = 'ADD_PENDING_FOLLOWER';
export const ADD_APPROVED_FOLLOWER = 'ADD_APPROVED_FOLLOWER';
export const REMOVE_APPROVED_FOLLOWER = 'REMOVE_APPROVED_FOLLOWER';
